blog_app/models.py
from blog_app import database
from werkzeug import generate_password_hash, check_password_hash
from flask_login import UserMixin, login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.get(user_id)


class User(database.Model, UserMixin):
    __tablename__ = 'users'
    id = database.column(database.Integer, primary_key=True)
    profile = database.column(database.String(20), nullable=False, defalult='a.jpg')
    username = database.column(database.String(64), unique=True, index=True)

    email = database.column(database.String(64), unique=True, index=True)
    password_hash = database.column(database.String(64))

    posts = database.relationship('Posts', backref='bhaibhai', lazy=True)

    def __init__(self, username, email, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Posts(database.Model):
    users = database.relationship(User)
    id = database.column(database.Integer, primary_key=True)
    user_id = database.column(database.Integer, database.ForeignKey('users.id'))
    date = database.column(database.DateTime, nullable=False, default=datetime.utcnow)
    title = database.column(database.String(64), nullable=False, defalult='a.jpg')
    text = database.column(database.Text(564), nullable=False)

    def __init__(self, user_id, title, text):
        self.user_id = user_id
        self.title = title
        self.text = text

blog_app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,ValidationError
from wtforms.validators import DataRequired,Email,EqualTo
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from blog_app.models import User
class Loginform(FlaskForm):
    email=StringField('enter email',validators=[DataRequired(),Email()])
    password=StringField('enter password',validators=[DataRequired()])
    submit=SubmitField('submit')

class Registerform(FlaskForm):
    username= StringField('enter username', validators=[DataRequired()])
    email = StringField('enter email', validators=[DataRequired(), Email()])
    password = StringField('enter password', validators=[DataRequired(),EqualTo('password2')])
    password2 = StringField('enter confirmed  password', validators=[DataRequired()])

    submit = SubmitField('submit')

    def check_email(self,field):
        if User.query.get(email=field.data).first():
            raise ValidationError('email already taken')
    def check_username(self,field):
        if User.query.get(username=field.data).first():
            raise ValidationError('username already taken')

class Updateform(FlaskForm):
    username = StringField('enter username', validators=[DataRequired()])
    email = StringField('enter email', validators=[DataRequired(), Email()])
    profile_picture=FileField('wanna update picture click here', validators=[FileAllowed(['jpg','png','jpeg'])])
    submit = SubmitField('submit')
    def check_email(self,field):
        if User.query.get(email=field.data).first():
            raise ValidationError('email already taken')
    def check_username(self,field):
        if User.query.get(username=field.data).first():
            raise ValidationError('username already taken')

blog_app/__init__.py
from flask_sqlalchemy import SQLAlchemy
import os
from flask_migrate import Migrate
from flask import Flask
from blog_app.main.views import main
from blog_app.error_handling.handers import error_handler
from flask_login import LoginManager

app = Flask(__name__)
basedirectory = os.path.abspath(os.path.dirname(__file__))
app.config['SQLAlchemy_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedirectory, 'data.sqlite')
app.config['SQLAlchemy_TRACK_MODIFICATIONS'] = False
database = SQLAlchemy()
Migrate(app, database)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

app.register_blueprint(main)
app.register_blueprint(error_handler)

blog_app/main/views.py
from flask import render_template, Blueprint, request

main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('main/home.html')


@main.route('/about')
def about():
    return render_template('main/about.html')

blog_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Welcome To The Blog </title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <a class="navbar-brand" href="{{url_for('main.home')}}">
    <img src="https://www.mylifeisajourney.com/uploads/6/3/4/1/6341410/avengersendgame_orig.jpg"width="30" height="30" alt="">
  </a>  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}">Home </a>
      </li>
  <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.about')}}">About </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}">Account </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}">Log In </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}">Log Out </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}">Create Post </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.home')}}">Register </a>
      </li>

    </ul>
  </div>
</nav>
<div class="container">
    {% block content %}
{% endblock %}
</div>

</body>
</html>

blog_app/templates/main/about.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
    <h1>about page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut corporis doloribus earum exercitationem illum ipsa laudantium magni molestiae nesciunt quia.</p>
    </div>
{% endblock %}

blog_app/templates/main/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Hello world</h1>
    <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
  </div>
</div>
{% endblock %}